name: sync

on:
  schedule:
    - cron: '25 21 * * 1-5'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Auto Commit Push
      run: git clone https://gitcode.net/m0_64980826/songge_tiku.git
